---
- hosts: all
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ user }}"
          visual_studio_code_extensions:
            - riccardonovaglia.missinglineendoffile
            - dbaeumer.vscode-eslint
            - bernardodsanderson.theme-material-neutral
            - shardulm94.trailing-spaces
            - eg2.tslint
            - emmanuelbeziat.vscode-great-icons
          visual_studio_code_settings: {
            "workbench.iconTheme": "vscode-great-icons",
    	      "workbench.colorTheme": "Material Neutral - Classic",
            "editor.rulers": [80, 100, 120],
            "files.trimTrailingWhitespace": true,
            "files.trimFinalNewlines": true,
            "files.insertFinalNewline": true,
            "trailing-spaces.trimOnSave": true,
          }
