---
- name: Creates nvim directories
  file:
        path: "{{ item }}"
        state: directory
  with_items:
        - ~/.config/nvim
        - ~/.config/nvim/autoload
        - ~/.config/nvim/bundle
        - ~/.config/nvim/bundle/ctrlp
        - ~/.config/nvim/bundle/nerdtree
        - ~/.config/nvim/bundle/nerdtree-git-plugin

- name: Install package manager
  get_url:
        url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
        dest: ~/.config/nvim/autoload/pathogen.vim

- name: Install plugins
  git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
  with_items:
    - "{{ plugins }}"

- name: Copies configuration file
  template:
        src: init.vim.j2
        dest: /home/{{ user }}/.config/nvim/init.vim
